name: Release Workflow

on:
  push:
    tags:
      - "release-request/v[0-9]+.[0-9]+.[0-9]+"
      - "release-request/v[0-9]+.[0-9]+.[0-9]+-SNAPSHOT*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  release:
    uses: diggsweden/reusable-ci/.github/workflows/release-orchestrator.yml@test/gradle-publish-e2e
    permissions:
      contents: write
      packages: write
      id-token: write
      actions: read
      attestations: write
      security-events: write
    secrets:
      RELEASE_GPG_PRIVATE_KEY: ${{ secrets.OSPO_BOT_GPG_PRIV }}
      RELEASE_GPG_PASSPHRASE: ${{ secrets.OSPO_BOT_GPG_PASS }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
      CODE_SCANNING_TOKEN: ${{ secrets.SARIF_UPLOAD_TOKEN }}
      RELEASE_GPG_PUBLIC_KEY: ${{ secrets.RELEASE_GPG_PUBLIC_KEY }}
      RELEASE_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}
    with:
      reusable-ci-binary-ref: test/gradle-publish-e2e
      artifacts-config: .github/artifacts.yml
      branch: test/reusable-3
      changelog-creator: git-cliff
      release-publisher: github-cli
      runtime-image: ghcr.io/diggsweden/reusable-ci-runtime-base:test-gradle-publish-e2e
      runtime-image-full: ghcr.io/diggsweden/reusable-ci-runtime:test-gradle-publish-e2e
      runtime-image-java: ghcr.io/diggsweden/reusable-ci-runtime-java-25:test-gradle-publish-e2e
      runtime-image-android: ghcr.io/diggsweden/reusable-ci-runtime-android-35:test-gradle-publish-e2e
